= TwoGather API Spec Docs
api spec 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

== Auth

=== Login
operation::auth/login/[snippets='http-request,request-fields,http-response,response-fields']

=== Consumer-Password-Verification
operation::consumer/verify-password/[snippets='http-request,request-fields,http-response,response-fields']

=== StoreOwner-Password-Verification
operation::owner/verify-password/[snippets='http-request,request-fields,http-response,response-fields']

== Admin
=== Get-Store
operation::admin/getStore/[snippets='http-request,path-parameters,http-response,response-fields']
=== Approve-Store
operation::admin/approve/[snippets='http-request,path-parameters']
=== Reject-Store
operation::admin/reject/[snippets='http-request,request-fields,path-parameters']


== Email
=== Email-Verification
operation::email/post/[snippets='http-request,request-fields,http-response,response-fields']

== Menu

=== Get
operation::menu/get/[snippets='http-request,path-parameters,http-response,response-fields']

=== Delete
operation::menu/delete/[snippets='http-request,path-parameters,request-fields,http-response']

=== Update
operation::menu/update/[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

== BusinessHour

=== Get
operation::business-hour/get/[snippets='http-request,path-parameters,http-response,response-fields']

=== Delete
operation::business-hour/delete/[snippets='http-request,path-parameters,request-fields,http-response']

=== Update
operation::business-hour/update/[snippets='http-request,path-parameters,request-fields,http-response,response-fields']


== Keyword
=== Get-List
operation::keywords/get/[snippets='http-request,request-parameters,http-response,response-fields']
=== Set-Keyword-Store-Association
operation::keywords/set-keyword-store/[snippets='http-request,request-body,path-parameters']

== Store

=== Save
operation::store/save/[snippets='http-request,path-parameters,request-parts,http-response,response-fields']

=== Get-One
operation::store/get-one/[snippets='http-request,path-parameters,http-response,response-fields']

=== Get-List
operation::store/get-list/[snippets='http-request,path-parameters,http-response,response-fields']

=== Get-List-Search
operation::store/get-list-search/[snippets='http-request,request-parameters,http-response,response-fields']

=== Get-My-Store-List
operation::store/get-my-list/[snippets='http-request,request-parameters,http-response,response-fields']

=== Delete
operation::store/delete/[snippets='http-request,path-parameters,http-response']

=== Update
operation::store/update/[snippets='http-request,path-parameters,request-fields,http-response,response-fields']


== Store-Owner

=== Get
operation::owner/get/[snippets='http-request,path-parameters,http-response,response-fields']

=== Save
operation::owner/save/[snippets='http-request,request-fields,http-response,response-fields']

=== Update
operation::owner/update/[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== Delete
operation::owner/delete/[snippets='http-request,path-parameters,http-response']

== Consumer

=== Get
operation::consumer/get/[snippets='http-request,path-parameters,http-response,response-fields']

=== Save
operation::consumer/save/[snippets='http-request,request-fields,http-response,response-fields']

=== Update
operation::consumer/update/[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

=== Delete
operation::consumer/delete/[snippets='http-request,path-parameters,http-response']

== Image

=== Get
operation::image/get/[snippets='http-request,path-parameters,http-response,response-fields']

=== Save
operation::image/save/[snippets='http-request,path-parameters,http-response,response-fields']

=== Delete
operation::image/delete/[snippets='http-request,path-parameters,http-response']


== Review

=== Get-My-Review-List
operation::review/getMyReviewInfos/[snippets='http-request,path-parameters,request-parameters,http-response,response-fields']

=== Save
operation::review/save/[snippets='http-request,path-parameters,http-response,response-fields']

=== Update
operation::review/update/[snippets='http-request,path-parameters,http-response,response-fields']

=== Delete
operation::review/delete/[snippets='http-request,path-parameters,http-response']

== Comment
=== Save
operation::comment/save/[snippets='http-request,path-parameters,http-response,response-fields']

=== Update
operation::comment/update/[snippets='http-request,path-parameters,http-response,response-fields']

=== Delete
operation::comment/delete/[snippets='http-request,path-parameters,http-response']

== Category

=== Get
operation::category/get/[snippets='http-request,http-response,response-fields']

== Like
=== AddLike
operation::like/setLike/[snippets='http-request,path-parameters']

=== DeleteLike
operation::like/deleteLike/[snippets='http-request,path-parameters']


:linkattrs:
:bookmarks: