= TwoGather API Spec Docs
api spec 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:


== BusinessHour API

=== Get
operation::business-hours/get/[snippets='http-request,http-response,response-fields']

=== Delete
operation::business-hours/delete/[snippets='http-request,request-fields,http-response']

=== Save
operation::business-hours/save/[snippets='http-request,request-fields,http-response,response-fields']

=== Update
operation::business-hours/update/[snippets='http-request,request-fields,http-response,response-fields']


== Stores API

=== Save
operation::store/save/[snippets='http-request,request-fields,http-response,response-fields']

=== Get-One
operation::store/get-one/[snippets='http-request,http-response,response-fields']

=== Get-List
operation::store/get-list/[snippets='http-request,http-response,response-fields']

=== Get-My-List
operation::store/get-my-list/[snippets='http-request,http-response,response-fields']





:linkattrs:
:bookmarks: