= TwoGather API Spec Docs
api spec 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:


== BusinessHour API

=== Get
operation::business-hour/get/[snippets='http-request,request-parameters,http-response,response-fields']

=== Delete
operation::business-hour/delete/[snippets='http-request,request-fields,http-response']

=== Save
operation::business-hour/save/[snippets='http-request,request-parameters,request-fields,http-response,response-fields']

=== Update
operation::business-hour/update/[snippets='http-request,request-fields,http-response,response-fields']


== Store API

=== Save
operation::store/save/[snippets='http-request,request-fields,http-response,response-fields']

=== Get-One
operation::store/get-one/[snippets='http-request,request-parameters,http-response,response-fields']

=== Get-List
operation::store/get-list/[snippets='http-request,request-parameters,http-response,response-fields']

=== Get-My-List
operation::store/get-my-list/[snippets='http-request,request-parameters,http-response,response-fields']

=== Delete
operation::store/delete/[snippets='http-request,request-parameters,http-response']

=== Update
operation::store/update/[snippets='http-request,request-fields,http-response,response-fields']


== Store-Owner API

=== Get
operation::owner/get/[snippets='http-request,path-parameters,http-response,response-fields']

=== Save
operation::owner/save/[snippets='http-request,request-fields,http-response,response-fields']

=== Update
operation::owner/update/[snippets='http-request,request-fields,http-response,response-fields']

=== Delete
operation::owner/delete/[snippets='http-request,path-parameters,http-response']




:linkattrs:
:bookmarks: